import type { ReactElement } from 'react'
import type { VizItem } from './components/Layout/Sidebar'
import { ParticlesVisualizer } from './visual/ParticlesVisualizer'
import { StarfieldVisualizer } from './visual/GalaxyVisualizer'
import { CircularVisualizer } from './visual/CircularVisualizer'
import { ShaderSphereVisualizer } from './visual/ShaderSphereVisualizer'
import { CardVisualizer } from './visual/CardVisualizer'
import { BarcodeVisualizer } from './visual/BarcodeVisualizer'
import { TunnelBarsVisualizer } from './visual/TunnelBarsVisualizer'
import { GeometryVisualizer } from './visual/GeometryVisualizer'
import { WitchscopeVisualizer } from './visual/WitchscopeVisualizer'
import { VibeVisualizer } from './visual/VibeVisualizer'
import { FaceVisualizer } from './visual/FaceVisualizer'
import { KaraokeVisualizer } from './visual/KaraokeVisualizer'
import { BeatGameVisualizer } from './visual/BeatGameVisualizer'
import { HaloVisualizer } from './visual/HaloVisualizer'
import { CosmicVisualizer } from './visual/CosmicVisualizer'

export type VisualizerMode =
  | 'cosmic'
  | 'circular'
  | 'particles'
  | 'sphere'
  | 'galaxy'
  | 'card'
  | 'barcode'
  | 'tunnelbars'
  | 'geometry'
  | 'witchscope'
  | 'vibe'
  | 'face'
  | 'karaoke'
  | 'beatgame'
  | 'halo'

export const VIZ_ITEMS: VizItem[] = [
]
